version: '3.9'
services:
  gitlab:
    image: gitlab-ce:latest
    restart: always
    hostname: gitlab
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.ua403error.com'
        gitlab_rails['time_zone'] =                     'Asia/Tehran'
        gitlab_rails['gitlab_email_from'] =             'sysadmin@ua403error.com'
        gitlab_rails['gitlab_email_display_name'] =     'GitLab Administrator'
        gitlab_rails['gitlab_email_reply_to'] =         'home@ua403error.com'
        gitlab_rails['backup_keep_time'] =              14515200
        gitlab_rails['smtp_enable'] =                   true
        gitlab_rails['smtp_address'] =                  "mail.ua403error.com"
        gitlab_rails['smtp_port'] =                     587
        gitlab_rails['smtp_user_name'] =                "sysadmin@ua403error.com"
        gitlab_rails['smtp_password'] =                 "S+r0ng_P@$$W0rDD"
        gitlab_rails['smtp_domain'] =                   "mail.ua403error.comr"
        gitlab_rails['smtp_authentication'] =           "login"
        gitlab_rails['smtp_enable_starttls_auto'] =     true
        logging['logrotate_frequency'] =                "weekly"
        logging['logrotate_rotate'] =                   52
        logging['logrotate_compress'] =                 "compress"
        logging['logrotate_method'] =                   "copytruncate"
        logging['logrotate_delaycompress'] =            "delaycompress"
        nginx['listen_port'] =                          443
        nginx['redirect_http_to_https'] =               true
        nginx['ssl_protocols'] =                        "TLSv1.1 TLSv1.2"
        nginx['logrotate_frequency'] =                  "weekly"
        nginx['logrotate_rotate'] =                     52
        nginx['logrotate_compress'] =                   "compress"
        nginx['logrotate_method'] =                     "copytruncate"
        nginx['logrotate_delaycompress'] =              "delaycompress"
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '/opt/gitlab-ce/config:/etc/gitlab'
      - '/opt/gitlab-ce/logs:/var/log/gitlab'
      - '/opt/gitlab-ce/data:/var/opt/gitlab'
      - '/opt/gitlab-ce/certs:/etc/gitlab/ssl'

